# Generated by Django 3.2.2 on 2021-05-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_auto_20210510_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='lstm1_scope',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='lstm2_scope',
            field=models.IntegerField(default=0),
        ),
    ]
